version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./public:/app/public
      - ./src:/app/src
    environment:
      - PORT=8080
      - WATCHPACK_POLLING=true
    ports:
      - '8080:8080'
    command: sh -c "${CMD:-npm run start}"
